// Sample essay data for Take a Look
// Korean-language essays about niche obsessions ("내가 왜 이걸 파게 됐는지")

const ESSAYS = [
  {
    id: 1,
    slug: "old-keyboards",
    title: "어느 날, 적축 키보드를 버렸다",
    titleEn: "On Letting Go of Linear Switches",
    excerpt: "조용한 게 능사는 아니라는 걸, 갈축 앞에서 알았다.",
    tags: ["키보드", "물성", "소리"],
    category: "OBJECT",
    date: "2026.04.28",
    readingTime: 7,
    cover: "https://picsum.photos/seed/keyboard-essay/1200/1600",
  },
  {
    id: 2,
    slug: "bus-seat",
    title: "버스 맨 뒷자리의 사회학",
    titleEn: "A Sociology of the Back Seat",
    excerpt: "왜 우리는 굳이 그 자리에 앉으려 했을까.",
    tags: ["도시", "관찰", "에세이"],
    category: "CULTURE",
    date: "2026.04.21",
    readingTime: 12,
    cover: "https://picsum.photos/seed/bus-rear/1200/1600",
  },
  {
    id: 3,
    slug: "convenience-coffee",
    title: "편의점 커피의 미학",
    titleEn: "Aesthetics of Convenience Store Coffee",
    excerpt: "1,500원짜리 라떼가 가르쳐준 것들.",
    tags: ["커피", "일상", "취향"],
    category: "TASTE",
    date: "2026.04.14",
    readingTime: 5,
    cover: "https://picsum.photos/seed/conv-coffee-9/1200/1600",
  },
  {
    id: 4,
    slug: "city-pop-revival",
    title: "다시 듣는 시티팝, 이번엔 다르다",
    titleEn: "City Pop, This Time Around",
    excerpt: "유튜브 알고리즘이 아니라, 내가 골랐다.",
    tags: ["음악", "80s", "기억"],
    category: "SOUND",
    date: "2026.04.07",
    readingTime: 9,
    cover: "https://picsum.photos/seed/citypop-night/1200/1600",
  },
  {
    id: 5,
    slug: "stationery-shop",
    title: "문방구가 사라진 동네에서",
    titleEn: "A Town Without Its Stationery Shop",
    excerpt: "사라진 건 가게가 아니라 어떤 시간이었다.",
    tags: ["문구", "동네", "노스탤지어"],
    category: "MEMORY",
    date: "2026.03.31",
    readingTime: 8,
    cover: "https://picsum.photos/seed/stationery-warm/1200/1600",
  },
  {
    id: 6,
    slug: "ramen-broth",
    title: "라멘집 국물의 첫 한 모금",
    titleEn: "The First Sip of Ramen Broth",
    excerpt: "맛보다 먼저, 온도가 들어온다.",
    tags: ["음식", "물성", "감각"],
    category: "TASTE",
    date: "2026.03.24",
    readingTime: 6,
    cover: "https://picsum.photos/seed/ramen-steam/1200/1600",
  },
  {
    id: 7,
    slug: "film-camera",
    title: "필름 카메라를 다시 든 이유",
    titleEn: "Why I Picked Up Film Again",
    excerpt: "기다리는 일이 곧 보는 일이 되었다.",
    tags: ["사진", "물성", "느림"],
    category: "OBJECT",
    date: "2026.03.17",
    readingTime: 11,
    cover: "https://picsum.photos/seed/film-cam-grain/1200/1600",
  },
  {
    id: 8,
    slug: "subway-window",
    title: "지하철 창밖, 3초의 풍경들",
    titleEn: "Three Seconds Out the Subway Window",
    excerpt: "어느 순간 모두가 핸드폰을 본다.",
    tags: ["도시", "관찰", "에세이"],
    category: "CITY",
    date: "2026.03.10",
    readingTime: 4,
    cover: "https://picsum.photos/seed/subway-glass/1200/1600",
  },
];

window.ESSAYS = ESSAYS;
